const mongoose = require('mongoose');

const clientSchema = new mongoose.Schema({
  code: {
    type: String,
    required: true,
  },
  rsoc: String,
  adresse: String,
  mf: String,
  ville: String,
  tel: String,
  respercon1: String,
  fax: String,
  percon1: String,
  telpercon1: String,
  emailpercon1: String,
  percon2: String,
  respercon2: String,
  telpercon2: String,
  emailpercon2: String,
  email: String,
  percon3: String,
  telpercon3: String,
  emailpercon3: String,
  respercon3: String,
  RC: String,
  CP: String,
  RIB: String,
  cville: String,
  banque: String,
  timbre: { type: String, default: "0" },
  exo: { type: String, default: "0" },
  susp: { type: String, default: "0" },
  reel: { type: String, default: "0" },
  datedebut: Date,
  datefin: Date,
  decision: String,
  export: { type: String, default: "0" },
  soldeinit: { type: Number, default: 0 },
  prix: String,
  mtreg: { type: Number, default: 0 },
  rap: { type: String, default: "N" },
  soldeinitbl: { type: Number, default: 0 },
  mtregbl: { type: Number, default: 0 },
  rapbl: { type: Number, default: 0 },
  rapbc: { type: String, default: "0" },
  remise: { type: Number, default: 0 },
  regime: { type: String, default: "R" },
  soldeinitbc: { type: Number, default: 0 },
  mtrapbc: { type: Number, default: 0 },
  soldeimp: { type: Number, default: 0 },
  scredit: { type: Number, default: 0 },
  srisque: { type: Number, default: 0 },
  delaireg: { type: Number, default: 0 },
  codetarif: String,
  libtarif: String,
  coderep: String,
  librep: String,
  codesect: String,
  libsect: String,
  codereg: String,
  libreg: String,
  codeact: String,
  libact: String,
  libpost: String,
  codetypreg: String,
  libtypreg: String,
  codebanq: String,
  adressefact: String,
  comptec: String,
  rsocar: String,
  datecreation: Date,
  datevalidation: Date,
  validation: { type: String, default: "0" },
  blocage: { type: String, default: "0" },
  message: String,
  tel2: String,
  numcompte: String,
  codegr: String,
  libgr: String,
  parunite: { type: String, default: "0" },
  adressear: String,
  tauxret: { type: Number, default: 0 },
  codequal: String,
  libqual: String,
  descl: String,
  prod: { type: String, default: "0" },
  adressebanque: String
});

const Client = mongoose.model('Client', clientSchema);

module.exports = Client;
