const mongoose = require('mongoose');


const personnelSchema = new mongoose.Schema({
    code: {
        type: String,
        required: true
    },
    libelle: {
        type: String,
        required: true
    },
      cin: String,
  cnss: String,
  nomprenom: String,
  adresse: String,
  codecat: String,
  libellecat: String,
  codech: String,
  libellech: String,
  echelle: String,
  situation: String,
  cheffamille: { type: String, default: '0' },
  nbenf: { type: Number, default: 0 },
  nbparent: { type: Number, default: 0 },
  acnss: { type: String, default: '0' },
  typetrav: String,
  tauxcnss: { type: Number, default: 0 },
  declarer: { type: String, default: '0' },
  salaire: { type: Number, default: 0 },
  nbjours: { type: Number, default: 0 },
  tauxjours: { type: Number, default: 0 },
  modepaie: String,
  banque: String,
  rib: String,
  agence: String,
  codecal: String,
  libcal: String,
  aimpot: { type: String, default: '0' },
  codeserv: String,
  libserv: String,
  cle: String,
  gerant: { type: String, default: '0' },
  datenais: Date,
  daterec: Date,
  tauxcnssp: { type: Number, default: 0 },
  choix: { type: String, default: '0' },
  codepoint: String,
  codeplan: String,
  libplan: String,
  clotannee: { type: String, default: '0' },
  totprime: { type: Number, default: 0 },
  nbenfanti: { type: Number, default: 0 },
  nbenfnbour: { type: Number, default: 0 },
  datedebech: Date,
  datefinech: Date,
  codecatav: String,
  libcatav: String,
  codenat: String,
  libnat: String,
  actif: { type: String, default: '0' },
  codebanq: String,
  libbanq: String,
  titulaire: { type: String, default: '0' },
  salnet: { type: Number, default: 0 },
  salaire1: { type: Number, default: 0 },
  nomprenomar: String,
  adressear: String,
  datecin: Date,
  lieucin: String,
  calificationar: String,
  tauxcong: { type: Number, default: 0 },
  codecaisse: String,
  typecont: { type: String, default: '0' },
  basebrcn: { type: Number, default: 0 },
  sansav: { type: String, default: '0' },


});

const Personnel = mongoose.model('Personnel', personnelSchema);

module.exports = Personnel;
